import { MainNav } from "@/components/navigation/main-nav";
import { RouterProvider } from "@/components/router-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { navbarLinks } from "@/config/navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import "@/app/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader showSpinner={false} color="#0284c7" shadow={false} />
          <header>
            <MainNav items={navbarLinks.main} />
          </header>

          <main className="flex-1">
            <RouterProvider>
              <NuqsAdapter>{children}</NuqsAdapter>
            </RouterProvider>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
